"""v4 = v2 picture with two REVERSED-MOTION fixes + generated video-to-foley audio layer.

Owner verdict on v3: SFX still a joke — library sounds placed by guesswork can't work, and two
clips actually play BACKWARDS (caught 2026-08-20 by the 6fps vision audit):
  - C33 (money shot): opens already-broken, halves CLOSE 0.7-1.9s then re-open -> start at 2.0s.
  - C29 (tray out of oven): a pull-out played backwards (tray goes IN) -> use C29R.mp4
    (time-reversed file = correct pull-out; verified on a 4fps strip).

Audio architecture change: the foley is GENERATED by MMAudio (video-to-audio) per exact shot
window — the model watches the same frames the viewer sees, so sync is intrinsic. Library
one-shots are gone. Foley bus is ducked under VO by a frame envelope in the assembler
(FOLEY_BASE/FOLEY_VO/FOLEY_ASMR). Prompts: foley_prompts_v4.json (from the vision audit).
Generator: gen_foley_v4.py -> assets/techjoint_cookies/foley_v4/<SHOT>.flac.
"""
import os
from cookies_v2_config import OVERRIDES as V2
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))

_hook = dict(V2["HOOK_SRC"])
_hook.update({
    "H1": ("C33", 2.0),      # bend-open: forward-motion window only
    "H3": ("C29R", 3.2),     # reversed file = real pull-out; motion starts ~3.0
    "C29": ("C29R", 1.75),   # payoff tray-out beat
})
_clip_in = dict(V2["CLIP_IN"]); _clip_in["C33"] = 2.0

OVERRIDES = dict(
    V2,
    HOOK_SRC=_hook,
    CLIP_IN=_clip_in,
    SFX_EVENTS={},            # library layer OFF — generated foley carries the video
    CLIP_AUDIO={},
    FOLEY_DIR=os.path.join(REPO, "assets", "techjoint_cookies", "foley_v4"),
    FOLEY_GAIN={},
    FOLEY_BASE=1.0, FOLEY_VO=0.5, FOLEY_ASMR=1.25, FOLEY_NORM_I=-16,
    # Competitor-measured sound design (5 viral hands-only refs, 2026-08-20):
    # foley IS the foreground (26-65 contact onsets/min, peaks 5-10dB under VO, zero stingers);
    # music quiet or absent, MUTED in the hook and the reveal; room tone fills gaps (-50dB),
    # and the pull-apart gets a pure-foley beat with the crack as the loudest event.
    MUSIC_BASE=0.12, MUSIC_DIP=0.07, MUSIC_CARD=0.30,
    MUSIC_MUTE_SPANS=[("H1", "C01"), ("C37", "C36")],
    ROOM_TONE=os.path.join(REPO, "assets", "techjoint_cookies", "sfx", "room_tone.mp3"),
    ROOM_TONE_VOL=0.03,
    # reveal discipline: VO reaction lands AFTER the tear (C33 window starts at the bend-open;
    # tear crackle ~0.2-2.3s in-shot), not on top of it
    VO_BLOCKS=[b if b[1] != "C33" else ("okay,", "C33", 2.4) for b in V2["VO_BLOCKS"]],
)
