#!/usr/bin/env python3
"""lib/assembly/render_edit_spec.py — config-driven edit-layer renderer (GATE 2 deliverable path).
An EDIT SPEC is JSON: {"fps":24,"size":"1920x1080","segments":[{"src":"take.mp4","t0":0,"t1":12,"ops":[...]}, ...],
 "cards":[{"stills":[...],"t_start":3.5,"each":0.4}], "audio": "mix.wav"}
ops (times are within-segment seconds): {"op":"punch","z0":1.6,"z1":1.0,"t0":1.375,"t1":1.375} | {"op":"whiteout","t":3.375,"dur":0.08}
 | {"op":"flash","t":11.5,"dur":0.08,"alpha":0.7} | {"op":"bloom","t":11.5,"dur":0.4,"amount":0.25}
 | {"op":"text","text":"30 DAYS","t_on":8.25,"t_off":10.35,"lead":0.3,"size":140,"y":"h*0.40","color":"white"}
Every op is a FREE edit-layer operation from lib.assembly.edit_layer; no pixels are generated by AI here.
Usage: render_edit_spec.py SPEC.json OUT.mp4
"""
import json, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from lib.assembly import edit_layer as E
def build_vf(ops, fps, W, H):
    parts = []
    for o in ops:
        k = o["op"]
        if k == "punch": parts.append(E.punch_in(o["z0"], o["z1"], o["t0"], o.get("t1", o["t0"]), fps, W, H))
        elif k == "whiteout": parts.append(E.whiteout(o["t"], o.get("dur", 0.10), o.get("alpha", 0.85)))
        elif k == "flash": parts.append(E.flash(o["t"], o.get("dur", 0.08), o.get("alpha", 0.6)))
        elif k == "bloom": parts.append(E.bloom(o["t"], o.get("dur", 0.25), o.get("amount", 0.3)))
        elif k == "text": parts.append(E.text_pop(o["text"], o["t_on"], o["t_off"], o.get("lead", 0.3), o.get("size", 96), o.get("y", "h*0.72"), o.get("color", "white"), o.get("pop", 1.15)))
        else: raise ValueError(f"unknown op {k}")
    return ",".join(parts)
def resolve_src(src, ledger, fallback=None):
    if src.startswith("ledger:"):
        sid = src.split(":",1)[1]
        row = (ledger or {}).get("clips", {}).get(sid)
        if row and row.get("verdict") == "PASS" and os.path.exists(row["clip"]): return row["clip"], "ledger"
        if fallback: return fallback, "FALLBACK"
        raise FileNotFoundError(f"no PASS-banked clip for {sid} and no --fallback")
    return src, "path"

def _dur(p):
    r = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", p], capture_output=True, text=True); return float(r.stdout.strip() or 0)

def main(spec_path, out, ledger_path=None, masters_dir=None, fallback=None, report_path=None, allow_loop=False, allow_replay=False):
    spec = json.load(open(spec_path)); fps = spec.get("fps", 24); W, H = map(int, spec.get("size", "1920x1080").split("x"))
    ledger = json.load(open(ledger_path)) if ledger_path and os.path.exists(ledger_path) else None
    work = os.path.splitext(out)[0] + "_segs"; os.makedirs(work, exist_ok=True); segs = []; rep = []
    # FAIL-CLOSED (2026-09-08 first-minute lesson): a slot longer than its clip would LOOP (visible jump); a setup replayed
    # outside a designed <=1.5 s insert is a REPEAT the viewer notices. Both refuse unless explicitly allowed (dry runs only).
    seen = {}; problems = []
    for sg in spec["segments"]:
        src, how = resolve_src(sg["src"], ledger, fallback); slot = (sg["t_out"] - sg["t_in"]) if "t_out" in sg else (sg["t1"] - sg["t0"]); t0 = sg.get("t0", 0.0)
        if how == "ledger" and not allow_loop and _dur(src) > 0 and t0 + slot > _dur(src) + 0.05: problems.append(f"{sg.get('shot')}: slot {slot:.2f}s from {t0:.2f}s exceeds clip {_dur(src):.2f}s (would LOOP)")
        key = sg["src"]; designed = (sg.get("reuse") == "insert" and slot <= 1.5)
        last = seen.get(key)
        is_return = sg.get("reuse") == "return" and last is not None and (sg.get("t_in", 0) - last["t_out"]) >= 8.0 and (abs(t0 - last["t0"]) >= 1.0 or any(o.get("op") == "punch" for o in sg.get("ops", [])))
        if last is not None and not designed and not is_return and not allow_replay: problems.append(f"{sg.get('shot')}: REPLAYS {key} for {slot:.2f}s (not a designed <=1.5 s insert nor a 'return' >=8 s later with a new in-point/zoom)")
        seen[key] = {"t_out": sg.get("t_out", 0), "t0": t0}
    if problems: raise SystemExit("render_edit_spec REFUSED (fix the cut, don't stretch it):\n  " + "\n  ".join(problems))
    for i, sg in enumerate(spec["segments"]):
        src, how = resolve_src(sg["src"], ledger, fallback)
        slot = (sg["t_out"] - sg["t_in"]) if "t_out" in sg else (sg["t1"] - sg["t0"])
        t0 = sg.get("t0", 0.0); t1 = t0 + slot
        ops = [o for o in sg.get("ops", []) if o.get("op") != "cards"]; cards = [o for o in sg.get("ops", []) if o.get("op") == "cards"]
        seg = os.path.join(work, f"seg{i:02d}_{sg.get('shot', i)}.mp4")
        vf = build_vf(ops, fps, W, H)
        E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-stream_loop", "-1", "-ss", f"{t0:.3f}", "-t", f"{slot:.3f}", "-i", src, "-vf", (f"scale={W}:{H}:force_original_aspect_ratio=decrease,pad={W}:{H}:(ow-iw)/2:(oh-ih)/2,fps={fps}" + ("," + vf if vf else "")), "-an", "-c:v", "libx264", "-preset", "veryfast", "-crf", "18", "-pix_fmt", "yuv420p", "-r", str(fps), seg])
        for c in cards:
            stills = []
            for st in c["stills"]:
                cand = os.path.join(masters_dir or "", st + ".png") if masters_dir else st
                stills.append(cand if os.path.exists(cand) else (fallback_still(work, st, W, H)))
            ins, chain, last = E.photo_cards_overlay(stills, c.get("t_start", 0.0), c.get("each", 0.4), W, H, c.get("card_w", 0.46), c.get("slide", 0.12))
            nxt = seg.replace(".mp4", "_cards.mp4")
            E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", seg] + ins + ["-filter_complex", chain, "-map", f"[{last}]", "-t", f"{slot:.3f}", "-an", "-c:v", "libx264", "-preset", "veryfast", "-crf", "18", "-pix_fmt", "yuv420p", "-r", str(fps), nxt]); seg = nxt
        segs.append(seg); rep.append({"shot": sg.get("shot"), "src": src, "how": how, "slot": round(slot, 3), "ops": len(ops), "cards": len(cards)})
    silent = os.path.join(work, "silent.mp4"); E.concat(segs, silent); cur = silent
    for j, c in enumerate(spec.get("cards", [])):
        ins, chain, last = E.photo_cards_overlay(c["stills"], c["t_start"], c["each"], W, H, c.get("card_w", 0.46), c.get("slide", 0.12))
        nxt = os.path.join(work, f"cards{j}.mp4")
        E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", cur] + ins + ["-filter_complex", chain, "-map", f"[{last}]", "-an", "-c:v", "libx264", "-preset", "veryfast", "-crf", "18", "-pix_fmt", "yuv420p", "-r", str(fps), nxt]); cur = nxt
    if spec.get("audio") and os.path.exists(spec["audio"]): E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", cur, "-i", spec["audio"], "-c:v", "copy", "-c:a", "aac", "-shortest", out])
    else: os.replace(cur, out)
    json.dump({"out": out, "segments": rep, "fallbacks": sum(r["how"] == "FALLBACK" for r in rep)}, open(report_path or out.replace(".mp4", "_report.json"), "w"), indent=1)
    print(f"rendered {out} ({len(rep)} segments, {sum(r['how']=='FALLBACK' for r in rep)} FALLBACK stand-ins)"); return out

def fallback_still(work, name, W, H):
    p = os.path.join(work, f"still_{name}.png")
    if not os.path.exists(p): E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-f", "lavfi", "-i", f"color=c=0x30343f:size={W//2}x{H//2}", "-vf", f"drawtext=fontfile={E.FONT}:text='{name}':fontsize=48:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2", "-frames:v", "1", p])
    return p

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(); ap.add_argument("spec"); ap.add_argument("out"); ap.add_argument("--ledger"); ap.add_argument("--masters"); ap.add_argument("--fallback", help="stand-in clip for unbanked ledger refs (prototype/dry runs ONLY; report counts them)"); ap.add_argument("--report"); ap.add_argument("--allow-loop", action="store_true", help="DRY RUNS ONLY"); ap.add_argument("--allow-replay", action="store_true", help="DRY RUNS ONLY")
    a = ap.parse_args(); main(a.spec, a.out, a.ledger, a.masters, a.fallback, a.report, a.allow_loop, a.allow_replay)
