#!/usr/bin/env python3
"""lib/assembly/render_edit_spec.py — config-driven edit-layer renderer (GATE 2 deliverable path).
An EDIT SPEC is JSON: {"fps":24,"size":"1920x1080","segments":[{"src":"take.mp4","t0":0,"t1":12,"ops":[...]}, ...],
 "cards":[{"stills":[...],"t_start":3.5,"each":0.4}], "audio": "mix.wav"}
ops (times are within-segment seconds): {"op":"punch","z0":1.6,"z1":1.0,"t0":1.375,"t1":1.375} | {"op":"whiteout","t":3.375,"dur":0.08}
 | {"op":"flash","t":11.5,"dur":0.08,"alpha":0.7} | {"op":"bloom","t":11.5,"dur":0.4,"amount":0.25}
 | {"op":"text","text":"30 DAYS","t_on":8.25,"t_off":10.35,"lead":0.3,"size":140,"y":"h*0.40","color":"white"}
Every op is a FREE edit-layer operation from lib.assembly.edit_layer; no pixels are generated by AI here.
Usage: render_edit_spec.py SPEC.json OUT.mp4
"""
import json, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from lib.assembly import edit_layer as E
def build_vf(ops, fps, W, H):
    parts = []
    for o in ops:
        k = o["op"]
        if k == "punch": parts.append(E.punch_in(o["z0"], o["z1"], o["t0"], o.get("t1", o["t0"]), fps, W, H))
        elif k == "whiteout": parts.append(E.whiteout(o["t"], o.get("dur", 0.10), o.get("alpha", 0.85)))
        elif k == "flash": parts.append(E.flash(o["t"], o.get("dur", 0.08), o.get("alpha", 0.6)))
        elif k == "bloom": parts.append(E.bloom(o["t"], o.get("dur", 0.25), o.get("amount", 0.3)))
        elif k == "text": parts.append(E.text_pop(o["text"], o["t_on"], o["t_off"], o.get("lead", 0.3), o.get("size", 96), o.get("y", "h*0.72"), o.get("color", "white"), o.get("pop", 1.15)))
        else: raise ValueError(f"unknown op {k}")
    return ",".join(parts)
def main(spec_path, out):
    spec = json.load(open(spec_path)); fps = spec.get("fps", 24); W, H = map(int, spec.get("size", "1920x1080").split("x"))
    work = os.path.splitext(out)[0] + "_segs"; os.makedirs(work, exist_ok=True); segs = []
    for i, sg in enumerate(spec["segments"]):
        seg = os.path.join(work, f"seg{i:02d}.mp4"); E.segment_from_take(sg["src"], sg["t0"], sg["t1"], build_vf(sg.get("ops", []), fps, W, H), seg, fps, W, H); segs.append(seg)
    silent = os.path.join(work, "silent.mp4"); E.concat(segs, silent); cur = silent
    for j, c in enumerate(spec.get("cards", [])):
        ins, chain, last = E.photo_cards_overlay(c["stills"], c["t_start"], c["each"], W, H, c.get("card_w", 0.46), c.get("slide", 0.12))
        nxt = os.path.join(work, f"cards{j}.mp4")
        E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", cur] + ins + ["-filter_complex", chain, "-map", f"[{last}]", "-an", "-c:v", "libx264", "-preset", "veryfast", "-crf", "18", "-pix_fmt", "yuv420p", "-r", str(fps), nxt]); cur = nxt
    if spec.get("audio") and os.path.exists(spec["audio"]): E.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-i", cur, "-i", spec["audio"], "-c:v", "copy", "-c:a", "aac", "-shortest", out])
    else: os.replace(cur, out)
    print("rendered", out); return out
if __name__ == "__main__": main(sys.argv[1], sys.argv[2])
